part of phone_field;

const List<PhoneFieldCountryEntity> _countries = [
  PhoneFieldCountryEntity(
    name: "Saudi Arabia",
    arabicName: "المملكة العربية السعودية",
    flag: "🇸🇦",
    code: "SA",
    dialCode: "966",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Egypt",
    arabicName: "مصر",
    flag: "🇪🇬",
    code: "EG",
    dialCode: "20",
    minLength: 10,
    maxLength: 10, // Without zero
  ),
  PhoneFieldCountryEntity(
    name: "United Arab Emirates",
    arabicName: "الإمارات العربية التحدة",
    flag: "🇦🇪",
    code: "AE",
    dialCode: "971",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Bahrain",
    arabicName: "البحرين",
    flag: "🇧🇭",
    code: "BH",
    dialCode: "973",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Iraq",
    arabicName: "العراق",
    flag: "🇮🇶",
    code: "IQ",
    dialCode: "964",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Kuwait",
    arabicName: "الكويت",
    flag: "🇰🇼",
    code: "KW",
    dialCode: "965",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Oman",
    arabicName: "عمان",
    flag: "🇴🇲",
    code: "OM",
    dialCode: "968",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Qatar",
    arabicName: "قطر",
    flag: "🇶🇦",
    code: "QA",
    dialCode: "974",
    minLength: 8,
    maxLength: 8,
  ),

  PhoneFieldCountryEntity(
    name: "Yemen",
    arabicName: "الجمهورية اليمنية",
    flag: "🇾🇪",
    code: "YE",
    dialCode: "967",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "United Kingdom",
    arabicName: "المملكة المتحدة",
    flag: "🇬🇧",
    code: "GB",
    dialCode: "44",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "United States",
    arabicName: "الولايات المتحدة الامريكية",
    flag: "🇺🇸",
    code: "US",
    dialCode: "1",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Tunisia",
    arabicName: "تونس",
    flag: "🇹🇳",
    code: "TN",
    dialCode: "216",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Turkey",
    arabicName: "تركيا",
    flag: "🇹🇷",
    code: "TR",
    dialCode: "90",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Turks and Caicos Islands",
    arabicName: "جزر تركس وكايكوس",
    flag: "🇹🇨",
    code: "TC",
    dialCode: "1649",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Afghanistan",
    flag: "🇦🇫",
    code: "AF",
    dialCode: "93",
    minLength: 9,
    maxLength: 9,
    arabicName: 'افغانستان',
  ),
  PhoneFieldCountryEntity(
    name: "Åland Islands",
    arabicName: "جزر آلاند",
    flag: "🇦🇽",
    code: "AX",
    dialCode: "358",
    minLength: 15,
    maxLength: 15,
  ),
  PhoneFieldCountryEntity(
    name: "Albania",
    arabicName: "ألبانيا",
    flag: "🇦🇱",
    code: "AL",
    dialCode: "355",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Algeria",
    arabicName: "الجزائر",
    flag: "🇩🇿",
    code: "DZ",
    dialCode: "213",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "American Samoa",
    arabicName: "ساموا الأمريكية",
    flag: "🇦🇸",
    code: "AS",
    dialCode: "1684",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Andorra",
    arabicName: "أندورا",
    flag: "🇦🇩",
    code: "AD",
    dialCode: "376",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Angola",
    arabicName: "أنجولا",
    flag: "🇦🇴",
    code: "AO",
    dialCode: "244",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Anguilla",
    arabicName: "أنجويلا",
    flag: "🇦🇮",
    code: "AI",
    dialCode: "1264",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Antarctica",
    arabicName: "القارة القطبية الجنوبية",
    flag: "🇦🇶",
    code: "AQ",
    dialCode: "672",
    minLength: 6,
    maxLength: 6,
  ),
  PhoneFieldCountryEntity(
    name: "Antigua and Barbuda",
    arabicName: "أنتيغوا وبربودا",
    flag: "🇦🇬",
    code: "AG",
    dialCode: "1268",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Argentina",
    arabicName: "الأرجنتين",
    flag: "🇦🇷",
    code: "AR",
    dialCode: "54",
    minLength: 12,
    maxLength: 12,
  ),
  PhoneFieldCountryEntity(
    name: "Armenia",
    arabicName: "أرمينيا",
    flag: "🇦🇲",
    code: "AM",
    dialCode: "374",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Aruba",
    arabicName: "أروبا",
    flag: "🇦🇼",
    code: "AW",
    dialCode: "297",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Australia",
    arabicName: "أستراليا",
    flag: "🇦🇺",
    code: "AU",
    dialCode: "61",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Austria",
    arabicName: "النمسا",
    flag: "🇦🇹",
    code: "AT",
    dialCode: "43",
    minLength: 13,
    maxLength: 13,
  ),
  PhoneFieldCountryEntity(
    name: "Azerbaijan",
    arabicName: "أذربيجان",
    flag: "🇦🇿",
    code: "AZ",
    dialCode: "994",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Bahamas",
    arabicName: "جزر البهاما",
    flag: "🇧🇸",
    code: "BS",
    dialCode: "1242",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Bangladesh",
    arabicName: "بنغلاديش",
    flag: "🇧🇩",
    code: "BD",
    dialCode: "880",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Barbados",
    arabicName: "بربادوس",
    flag: "🇧🇧",
    code: "BB",
    dialCode: "1246",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Belarus",
    arabicName: "بيلاروسيا",
    flag: "🇧🇾",
    code: "BY",
    dialCode: "375",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Belgium",
    arabicName: "بلجيكا",
    flag: "🇧🇪",
    code: "BE",
    dialCode: "32",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Belize",
    arabicName: "بليز",
    flag: "🇧🇿",
    code: "BZ",
    dialCode: "501",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Benin",
    arabicName: "بنين",
    flag: "🇧🇯",
    code: "BJ",
    dialCode: "229",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Bermuda",
    arabicName: "برمودا",
    flag: "🇧🇲",
    code: "BM",
    dialCode: "1441",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Bhutan",
    arabicName: "بوتان",
    flag: "🇧🇹",
    code: "BT",
    dialCode: "975",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Bolivia, Plurinational State of bolivia",
    arabicName: "بوليفيا، دولة بوليفيا المتعددة القوميات",
    flag: "🇧🇴",
    code: "BO",
    dialCode: "591",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Bosnia and Herzegovina",
    arabicName: "البوسنة والهرسك",
    flag: "🇧🇦",
    code: "BA",
    dialCode: "387",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Botswana",
    arabicName: "بوتسوانا",
    flag: "🇧🇼",
    code: "BW",
    dialCode: "267",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Bouvet Island",
    arabicName: "جزيرة بوفيه",
    flag: "🇧🇻",
    code: "BV",
    dialCode: "47",
    minLength: 15,
    maxLength: 15,
  ),
  PhoneFieldCountryEntity(
    name: "Brazil",
    arabicName: "البرازيل",
    flag: "🇧🇷",
    code: "BR",
    dialCode: "55",
    minLength: 11,
    maxLength: 11,
  ),
  PhoneFieldCountryEntity(
    name: "British Indian Ocean Territory",
    arabicName: "إقليم المحيط البريطاني الهندي",
    flag: "🇮🇴",
    code: "IO",
    dialCode: "246",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Brunei Darussalam",
    arabicName: "بروناي دار السلام",
    flag: "🇧🇳",
    code: "BN",
    dialCode: "673",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Bulgaria",
    arabicName: "بلغاريا",
    flag: "🇧🇬",
    code: "BG",
    dialCode: "359",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Burkina Faso",
    arabicName: "بوركينا فاسو",
    flag: "🇧🇫",
    code: "BF",
    dialCode: "226",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Burundi",
    arabicName: "بوروندي",
    flag: "🇧🇮",
    code: "BI",
    dialCode: "257",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Cambodia",
    arabicName: "كمبوديا",
    flag: "🇰🇭",
    code: "KH",
    dialCode: "855",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Cameroon",
    arabicName: "الكاميرون",
    flag: "🇨🇲",
    code: "CM",
    dialCode: "237",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Italia",
    arabicName: "بطل إيطاليا",
    flag: "🇮🇹",
    code: "IT",
    dialCode: "41",
    regionCode: "91",
    minLength: 13,
    maxLength: 13,
  ),
  PhoneFieldCountryEntity(
    name: "Canada",
    arabicName: "كندا",
    flag: "🇨🇦",
    code: "CA",
    dialCode: "1",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Cape Verde",
    arabicName: "الرأس الأخضر",
    flag: "🇨🇻",
    code: "CV",
    dialCode: "238",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Cayman Islands",
    arabicName: "جزر كايمان",
    flag: "🇰🇾",
    code: "KY",
    dialCode: "345",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Central African Republic",
    arabicName: "جمهورية افريقيا الوسطى",
    flag: "🇨🇫",
    code: "CF",
    dialCode: "236",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Chad",
    arabicName: "تشاد",
    flag: "🇹🇩",
    code: "TD",
    dialCode: "235",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Chile",
    arabicName: "شيلي",
    flag: "🇨🇱",
    code: "CL",
    dialCode: "56",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "China",
    arabicName: "الصين",
    flag: "🇨🇳",
    code: "CN",
    dialCode: "86",
    minLength: 12,
    maxLength: 12,
  ),
  PhoneFieldCountryEntity(
    name: "Christmas Island",
    arabicName: "جزيرة عيد الميلاد",
    flag: "🇨🇽",
    code: "CX",
    dialCode: "61",
    minLength: 15,
    maxLength: 15,
  ),
  PhoneFieldCountryEntity(
    name: "Cocos (Keeling) Islands",
    arabicName: "جزر كوكوس (كيلينغ)",
    flag: "🇨🇨",
    code: "CC",
    dialCode: "61",
    minLength: 15,
    maxLength: 15,
  ),
  PhoneFieldCountryEntity(
    name: "Columbia",
    arabicName: "كولومبيا",
    flag: "🇨🇴",
    code: "CO",
    dialCode: "57",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Comoros",
    arabicName: "جزر القمر",
    flag: "🇰🇲",
    code: "KM",
    dialCode: "269",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Congo",
    arabicName: "الكونغو",
    flag: "🇨🇬",
    code: "CG",
    dialCode: "242",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Congo, The Democratic Republic of the Congo",
    arabicName: "الكونغو، جمهورية الكونغو الديمقراطية",
    flag: "🇨🇩",
    code: "CD",
    dialCode: "243",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Cook Islands",
    arabicName: "جزر كوك",
    flag: "🇨🇰",
    code: "CK",
    dialCode: "682",
    minLength: 5,
    maxLength: 5,
  ),
  PhoneFieldCountryEntity(
    name: "Costa Rica",
    arabicName: "كوستا ريكا",
    flag: "🇨🇷",
    code: "CR",
    dialCode: "506",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Côte d'Ivoire",
    arabicName: "ساحل العاج",
    flag: "🇨🇮",
    code: "CI",
    dialCode: "225",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Croatia",
    arabicName: "كرواتيا",
    flag: "🇭🇷",
    code: "HR",
    dialCode: "385",
    minLength: 12,
    maxLength: 12,
  ),
  PhoneFieldCountryEntity(
    name: "Cuba",
    arabicName: "كوبا",
    flag: "🇨🇺",
    code: "CU",
    dialCode: "53",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Cyprus",
    arabicName: "قبرص",
    flag: "🇨🇾",
    code: "CY",
    dialCode: "357",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Czech Republic",
    arabicName: "الجمهورية التشيكية",
    flag: "🇨🇿",
    code: "CZ",
    dialCode: "420",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Denmark",
    arabicName: "الدنمارك",
    flag: "🇩🇰",
    code: "DK",
    dialCode: "45",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Djibouti",
    arabicName: "جيبوتي",
    flag: "🇩🇯",
    code: "DJ",
    dialCode: "253",
    minLength: 6,
    maxLength: 6,
  ),
  PhoneFieldCountryEntity(
    name: "Dominica",
    arabicName: "دومينيكا",
    flag: "🇩🇲",
    code: "DM",
    dialCode: "1767",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Dominican Republic",
    arabicName: "جمهورية الدومينيكان",
    flag: "🇩🇴",
    code: "DO",
    dialCode: "1849",
    minLength: 12,
    maxLength: 12,
  ),
  PhoneFieldCountryEntity(
    name: "Ecuador",
    arabicName: "الاكوادور",
    flag: "🇪🇨",
    code: "EC",
    dialCode: "593",
    minLength: 8,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "El Salvador",
    arabicName: "السلفادور",
    flag: "🇸🇻",
    code: "SV",
    dialCode: "503",
    minLength: 11,
    maxLength: 11,
  ),
  PhoneFieldCountryEntity(
    name: "Equatorial Guinea",
    arabicName: "غينيا الإستوائية",
    flag: "🇬🇶",
    code: "GQ",
    dialCode: "240",
    minLength: 6,
    maxLength: 6,
  ),
  PhoneFieldCountryEntity(
    name: "Eritrea",
    arabicName: "إريتريا",
    flag: "🇪🇷",
    code: "ER",
    dialCode: "291",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Estonia",
    arabicName: "إستونيا",
    flag: "🇪🇪",
    code: "EE",
    dialCode: "372",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Ethiopia",
    arabicName: "أثيوبيا",
    flag: "🇪🇹",
    code: "ET",
    dialCode: "251",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Falkland Islands (Malvinas)",
    arabicName: "جزر فوكلاند (مالفيناس)",
    flag: "🇫🇰",
    code: "FK",
    dialCode: "500",
    minLength: 5,
    maxLength: 5,
  ),
  PhoneFieldCountryEntity(
    name: "Faroe Islands",
    arabicName: "جزر فاروس",
    flag: "🇫🇴",
    code: "FO",
    dialCode: "298",
    minLength: 6,
    maxLength: 6,
  ),
  PhoneFieldCountryEntity(
    name: "Fiji",
    arabicName: "فيجي",
    flag: "🇫🇯",
    code: "FJ",
    dialCode: "679",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Finland",
    arabicName: "فنلندا",
    flag: "🇫🇮",
    code: "FI",
    dialCode: "358",
    minLength: 12,
    maxLength: 12,
  ),
  PhoneFieldCountryEntity(
    name: "France",
    arabicName: "فرنسا",
    flag: "🇫🇷",
    code: "FR",
    dialCode: "33",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "French Guiana",
    arabicName: "غيانا الفرنسية",
    flag: "🇬🇫",
    code: "GF",
    dialCode: "594",
    minLength: 15,
    maxLength: 15,
  ),
  PhoneFieldCountryEntity(
    name: "French Polynesia",
    arabicName: "بولينيزيا الفرنسية",
    flag: "🇵🇫",
    code: "PF",
    dialCode: "689",
    minLength: 6,
    maxLength: 6,
  ),
  PhoneFieldCountryEntity(
    name: "French Southern Territories",
    arabicName: "المناطق الجنوبية لفرنسا",
    flag: "🇹🇫",
    code: "TF",
    dialCode: "262",
    minLength: 15,
    maxLength: 15,
  ),
  PhoneFieldCountryEntity(
    name: "Gabon",
    arabicName: "الجابون",
    flag: "🇬🇦",
    code: "GA",
    dialCode: "241",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Gambia",
    arabicName: "غامبيا",
    flag: "🇬🇲",
    code: "GM",
    dialCode: "220",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Georgia",
    arabicName: "جورجيا",
    flag: "🇬🇪",
    code: "GE",
    dialCode: "995",
    minLength: 8,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Germany",
    arabicName: "ألمانيا",
    flag: "🇩🇪",
    code: "DE",
    dialCode: "49",
    minLength: 9,
    maxLength: 13,
  ),
  PhoneFieldCountryEntity(
    name: "Ghana",
    arabicName: "غانا",
    flag: "🇬🇭",
    code: "GH",
    dialCode: "233",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Gibraltar",
    arabicName: "جبل طارق",
    flag: "🇬🇮",
    code: "GI",
    dialCode: "350",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Greece",
    arabicName: "اليونان",
    flag: "🇬🇷",
    code: "GR",
    dialCode: "30",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Greenland",
    arabicName: "جزيرة جرينلاند",
    flag: "🇬🇱",
    code: "GL",
    dialCode: "299",
    minLength: 6,
    maxLength: 6,
  ),
  PhoneFieldCountryEntity(
    name: "Grenada",
    arabicName: "غرينادا",
    flag: "🇬🇩",
    code: "GD",
    dialCode: "1473",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Guadeloupe",
    arabicName: "جوادلوب",
    flag: "🇬🇵",
    code: "GP",
    dialCode: "590",
    minLength: 15,
    maxLength: 15,
  ),
  PhoneFieldCountryEntity(
    name: "Guam",
    arabicName: "غوام",
    flag: "🇬🇺",
    code: "GU",
    dialCode: "1671",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Guatemala",
    arabicName: "غواتيمالا",
    flag: "🇬🇹",
    code: "GT",
    dialCode: "502",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Guernsey",
    arabicName: "غيرنسي",
    flag: "🇬🇬",
    code: "GG",
    dialCode: "44",
    regionCode: "1481",
    minLength: 6,
    maxLength: 6,
  ),
  PhoneFieldCountryEntity(
    name: "Guinea",
    arabicName: "غينيا",
    flag: "🇬🇳",
    code: "GN",
    dialCode: "224",
    minLength: 8,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Guinea-Bissau",
    arabicName: "غينيا بيساو",
    flag: "🇬🇼",
    code: "GW",
    dialCode: "245",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Guyana",
    arabicName: "غيانا",
    flag: "🇬🇾",
    code: "GY",
    dialCode: "592",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Haiti",
    arabicName: "هايتي",
    flag: "🇭🇹",
    code: "HT",
    dialCode: "509",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Heard Island and Mcdonald Islands",
    arabicName: "قلب الجزيرة وجزر ماكدونالز",
    flag: "🇭🇲",
    code: "HM",
    dialCode: "672",
    minLength: 15,
    maxLength: 15,
  ),
  PhoneFieldCountryEntity(
    name: "Holy See (Vatican City State)",
    arabicName: "الكرسي الرسولي (دولة مدينة الفاتيكان)",
    flag: "🇻🇦",
    code: "VA",
    dialCode: "379",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Honduras",
    arabicName: "هندوراس",
    flag: "🇭🇳",
    code: "HN",
    dialCode: "504",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Hong Kong",
    arabicName: "هونج كونج",
    flag: "🇭🇰",
    code: "HK",
    dialCode: "852",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Hungary",
    arabicName: "المجر",
    flag: "🇭🇺",
    code: "HU",
    dialCode: "36",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Iceland",
    arabicName: "أيسلندا",
    flag: "🇮🇸",
    code: "IS",
    dialCode: "354",
    minLength: 7,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "India",
    arabicName: "الهند",
    flag: "🇮🇳",
    code: "IN",
    dialCode: "91",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Indonesia",
    arabicName: "إندونيسيا",
    flag: "🇮🇩",
    code: "ID",
    dialCode: "62",
    minLength: 10,
    maxLength: 13,
  ),
  PhoneFieldCountryEntity(
    name: "Iran, Islamic Republic of Persian Gulf",
    arabicName: "إيران، جمهورية الخليج الإسلامي",
    flag: "🇮🇷",
    code: "IR",
    dialCode: "98",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Ireland",
    arabicName: "أيرلندا",
    flag: "🇮🇪",
    code: "IE",
    dialCode: "353",
    minLength: 7,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Morocco",
    arabicName: "المغرب",
    flag: "🇲🇦",
    code: "MA",
    dialCode: "212",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Jordan",
    arabicName: "الاردن",
    flag: "🇯🇴",
    code: "JO",
    dialCode: "962",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Kenya",
    arabicName: "كينيا",
    flag: "🇰🇪",
    code: "KE",
    dialCode: "254",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Lebanon",
    arabicName: "لبنان",
    flag: "🇱🇧",
    code: "LB",
    dialCode: "961",
    minLength: 8,
    maxLength: 8,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Isle of Man",
  //   flag: "🇮🇲",
  //   code: "IM",
  //   dialCode: "44",
  //   regionCode: "1624",
  //   minLength: 6,
  //   maxLength: 6,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Israel",
  //   flag: "🇮🇱",
  //   code: "IL",
  //   dialCode: "972",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  PhoneFieldCountryEntity(
    name: "Italy",
    arabicName: "ايطاليا",
    flag: "🇮🇹",
    code: "IT",
    dialCode: "39",
    minLength: 13,
    maxLength: 13,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Jamaica",
  //   flag: "🇯🇲",
  //   code: "JM",
  //   dialCode: "1876",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  PhoneFieldCountryEntity(
    name: "Japan",
    arabicName: "اليابان",
    flag: "🇯🇵",
    code: "JP",
    dialCode: "81",
    minLength: 10,
    maxLength: 10,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Jersey",
  //   flag: "🇯🇪",
  //   code: "JE",
  //   dialCode: "44",
  //   regionCode: "1534",
  //   minLength: 6,
  //   maxLength: 6,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Kazakhstan",
  //   flag: "🇰🇿",
  //   code: "KZ",
  //   dialCode: "7",
  //   minLength: 10,
  //   maxLength: 10,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Kiribati",
  //   flag: "🇰🇮",
  //   code: "KI",
  //   dialCode: "686",
  //   minLength: 5,
  //   maxLength: 5,
  // ),
  PhoneFieldCountryEntity(
    name: "Korea, Democratic People's Republic of Korea",
    arabicName: "كوريا الشمالية",
    flag: "🇰🇵",
    code: "KP",
    dialCode: "850",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Korea, Republic of South Korea",
    arabicName: "كوريا الجنوبية",
    flag: "🇰🇷",
    code: "KR",
    dialCode: "82",
    minLength: 11,
    maxLength: 11,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Kosovo",
  //   flag: "🇽🇰",
  //   code: "XK",
  //   dialCode: "383",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Kyrgyzstan",
  //   flag: "🇰🇬",
  //   code: "KG",
  //   dialCode: "996",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Laos",
  //   flag: "🇱🇦",
  //   code: "LA",
  //   dialCode: "856",
  //   minLength: 10,
  //   maxLength: 10,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Latvia",
  //   flag: "🇱🇻",
  //   code: "LV",
  //   dialCode: "371",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Lesotho",
  //   flag: "🇱🇸",
  //   code: "LS",
  //   dialCode: "266",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  PhoneFieldCountryEntity(
    name: "Liberia",
    arabicName: "ليبيريا",
    flag: "🇱🇷",
    code: "LR",
    dialCode: "231",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Libyan Arab Jamahiriya",
    arabicName: "ليبيا",
    flag: "🇱🇾",
    code: "LY",
    dialCode: "218",
    minLength: 9,
    maxLength: 9,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Liechtenstein",
  //   flag: "🇱🇮",
  //   code: "LI",
  //   dialCode: "423",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Lithuania",
  //   flag: "🇱🇹",
  //   code: "LT",
  //   dialCode: "370",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Luxembourg",
  //   flag: "🇱🇺",
  //   code: "LU",
  //   dialCode: "352",
  //   minLength: 11,
  //   maxLength: 11,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Macao",
  //   flag: "🇲🇴",
  //   code: "MO",
  //   dialCode: "853",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Macedonia",
  //   flag: "🇲🇰",
  //   code: "MK",
  //   dialCode: "389",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  PhoneFieldCountryEntity(
    name: "Madagascar",
    arabicName: "مدغشقر",
    flag: "🇲🇬",
    code: "MG",
    dialCode: "261",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Malawi",
    arabicName: "ملاوي",
    flag: "🇲🇼",
    code: "MW",
    dialCode: "265",
    minLength: 7,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Malaysia",
    arabicName: "ماليزيا",
    flag: "🇲🇾",
    code: "MY",
    dialCode: "60",
    minLength: 11,
    maxLength: 11,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Maldives",
  //   flag: "🇲🇻",
  //   code: "MV",
  //   dialCode: "960",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Mali",
  //   flag: "🇲🇱",
  //   code: "ML",
  //   dialCode: "223",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Malta",
  //   flag: "🇲🇹",
  //   code: "MT",
  //   dialCode: "356",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Marshall Islands",
  //   flag: "🇲🇭",
  //   code: "MH",
  //   dialCode: "692",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Martinique",
  //   flag: "🇲🇶",
  //   code: "MQ",
  //   dialCode: "596",
  //   minLength: 15,
  //   maxLength: 15,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Mauritania",
  //   flag: "🇲🇷",
  //   code: "MR",
  //   dialCode: "222",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Mauritius",
  //   flag: "🇲🇺",
  //   code: "MU",
  //   dialCode: "230",
  //   minLength: 7,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Mayotte",
  //   flag: "🇾🇹",
  //   code: "YT",
  //   dialCode: "262",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  PhoneFieldCountryEntity(
    name: "Mexico",
    arabicName: "المكسيك",
    flag: "🇲🇽",
    code: "MX",
    dialCode: "52",
    minLength: 10,
    maxLength: 10,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Micronesia, Federated States of Micronesia",
  //   flag: "🇫🇲",
  //   code: "FM",
  //   dialCode: "691",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Moldova",
  //   flag: "🇲🇩",
  //   code: "MD",
  //   dialCode: "373",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Monaco",
  //   flag: "🇲🇨",
  //   code: "MC",
  //   dialCode: "377",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Mongolia",
  //   flag: "🇲🇳",
  //   code: "MN",
  //   dialCode: "976",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Montenegro",
  //   flag: "🇲🇪",
  //   code: "ME",
  //   dialCode: "382",
  //   minLength: 12,
  //   maxLength: 12,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Montserrat",
  //   flag: "🇲🇸",
  //   code: "MS",
  //   dialCode: "1664",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Mozambique",
  //   flag: "🇲🇿",
  //   code: "MZ",
  //   dialCode: "258",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Myanmar",
  //   flag: "🇲🇲",
  //   code: "MM",
  //   dialCode: "95",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Namibia",
  //   flag: "🇳🇦",
  //   code: "NA",
  //   dialCode: "264",
  //   minLength: 10,
  //   maxLength: 10,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Nauru",
  //   flag: "🇳🇷",
  //   code: "NR",
  //   dialCode: "674",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Nepal",
  //   flag: "🇳🇵",
  //   code: "NP",
  //   dialCode: "977",
  //   minLength: 10,
  //   maxLength: 10,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Netherlands",
  //   flag: "🇳🇱",
  //   code: "NL",
  //   dialCode: "31",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Netherlands Antilles",
  //   flag: "",
  //   code: "AN",
  //   dialCode: "599",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "New Caledonia",
  //   flag: "🇳🇨",
  //   code: "NC",
  //   dialCode: "687",
  //   minLength: 6,
  //   maxLength: 6,
  // ),
  PhoneFieldCountryEntity(
    name: "New Zealand",
    arabicName: "نيوزيلاندا",
    flag: "🇳🇿",
    code: "NZ",
    dialCode: "64",
    minLength: 10,
    maxLength: 10,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Nicaragua",
  //   flag: "🇳🇮",
  //   code: "NI",
  //   dialCode: "505",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  PhoneFieldCountryEntity(
    name: "Niger",
    arabicName: "النيجر",
    flag: "🇳🇪",
    code: "NE",
    dialCode: "227",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Nigeria",
    arabicName: "نيجيريا",
    flag: "🇳🇬",
    code: "NG",
    dialCode: "234",
    minLength: 10,
    maxLength: 11,
  ),
  PhoneFieldCountryEntity(
    name: "Niue",
    arabicName: "نيوي",
    flag: "🇳🇺",
    code: "NU",
    dialCode: "683",
    minLength: 4,
    maxLength: 4,
  ),
  PhoneFieldCountryEntity(
    name: "Norfolk Island",
    arabicName: "جزيرة نورفولك",
    flag: "🇳🇫",
    code: "NF",
    dialCode: "672",
    minLength: 15,
    maxLength: 15,
  ),
  PhoneFieldCountryEntity(
    name: "Northern Mariana Islands",
    arabicName: "جزر ماريانا الشمالية",
    flag: "🇲🇵",
    code: "MP",
    dialCode: "1670",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Norway",
    arabicName: "النرويج",
    flag: "🇳🇴",
    code: "NO",
    dialCode: "47",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Pakistan",
    arabicName: "باكستان",
    flag: "🇵🇰",
    code: "PK",
    dialCode: "92",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Palau",
    arabicName: "بالاو",
    flag: "🇵🇼",
    code: "PW",
    dialCode: "680",
    minLength: 7,
    maxLength: 7,
  ),
  PhoneFieldCountryEntity(
    name: "Palestine",
    arabicName: "فلسطين",
    flag: "🇵🇸",
    code: "PS",
    dialCode: "970",
    minLength: 9,
    maxLength: 9,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Panama",
  //   flag: "🇵🇦",
  //   code: "PA",
  //   dialCode: "507",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Papua New Guinea",
  //   flag: "🇵🇬",
  //   code: "PG",
  //   dialCode: "675",
  //   minLength: 11,
  //   maxLength: 11,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Paraguay",
  //   flag: "🇵🇾",
  //   code: "PY",
  //   dialCode: "595",
  //   minLength: 10,
  //   maxLength: 10,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Peru",
  //   flag: "🇵🇪",
  //   code: "PE",
  //   dialCode: "51",
  //   minLength: 11,
  //   maxLength: 11,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Philippines",
  //   flag: "🇵🇭",
  //   code: "PH",
  //   dialCode: "63",
  //   minLength: 10,
  //   maxLength: 10,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Pitcairn",
  //   flag: "🇵🇳",
  //   code: "PN",
  //   dialCode: "64",
  //   minLength: 10,
  //   maxLength: 10,
  // ),
  PhoneFieldCountryEntity(
    name: "Poland",
    arabicName: "بولندا",
    flag: "🇵🇱",
    code: "PL",
    dialCode: "48",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Portugal",
    arabicName: "البرتغال",
    flag: "🇵🇹",
    code: "PT",
    dialCode: "351",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Puerto Rico",
    arabicName: "بورتوريكو",
    flag: "🇵🇷",
    code: "PR",
    dialCode: "1939",
    minLength: 15,
    maxLength: 15,
  ),
  PhoneFieldCountryEntity(
    name: "Romania",
    arabicName: "رومانيا",
    flag: "🇷🇴",
    code: "RO",
    dialCode: "40",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Russia",
    arabicName: "روسيا",
    flag: "🇷🇺",
    code: "RU",
    dialCode: "7",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Rwanda",
    arabicName: "رواندا",
    flag: "🇷🇼",
    code: "RW",
    dialCode: "250",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Reunion",
    arabicName: "ريونيون",
    flag: "🇷🇪",
    code: "RE",
    dialCode: "262",
    minLength: 9,
    maxLength: 9,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Saint Barthelemy",
  //   flag: "🇧🇱",
  //   code: "BL",
  //   dialCode: "590",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Saint Helena, Ascension and Tristan Da Cunha",
  //   flag: "🇸🇭",
  //   code: "SH",
  //   dialCode: "290",
  //   minLength: 4,
  //   maxLength: 4,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Saint Kitts and Nevis",
  //   flag: "🇰🇳",
  //   code: "KN",
  //   dialCode: "1869",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Saint Lucia",
  //   flag: "🇱🇨",
  //   code: "LC",
  //   dialCode: "1758",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Saint Martin",
  //   flag: "🇲🇫",
  //   code: "MF",
  //   dialCode: "590",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Saint Pierre and Miquelon",
  //   flag: "🇵🇲",
  //   code: "PM",
  //   dialCode: "508",
  //   minLength: 6,
  //   maxLength: 6,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Saint Vincent and the Grenadines",
  //   flag: "🇻🇨",
  //   code: "VC",
  //   dialCode: "1784",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Samoa",
  //   flag: "🇼🇸",
  //   code: "WS",
  //   dialCode: "685",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "San Marino",
  //   flag: "🇸🇲",
  //   code: "SM",
  //   dialCode: "378",
  //   minLength: 10,
  //   maxLength: 10,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Sao Tome and Principe",
  //   flag: "🇸🇹",
  //   code: "ST",
  //   dialCode: "239",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  PhoneFieldCountryEntity(
    name: "Senegal",
    arabicName: "السنغال",
    flag: "🇸🇳",
    code: "SN",
    dialCode: "221",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Serbia",
    arabicName: "صربيا",
    flag: "🇷🇸",
    code: "RS",
    dialCode: "381",
    minLength: 12,
    maxLength: 12,
  ),
  PhoneFieldCountryEntity(
    name: "Seychelles",
    arabicName: "سيشيل",
    flag: "🇸🇨",
    code: "SC",
    dialCode: "248",
    minLength: 6,
    maxLength: 6,
  ),
  PhoneFieldCountryEntity(
    name: "Sierra Leone",
    arabicName: "سيراليون",
    flag: "🇸🇱",
    code: "SL",
    dialCode: "232",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Singapore",
    arabicName: "سينغابور",
    flag: "🇸🇬",
    code: "SG",
    dialCode: "65",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Slovakia",
    arabicName: "سلوفاكيا",
    flag: "🇸🇰",
    code: "SK",
    dialCode: "421",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Slovenia",
    arabicName: "سلوفينيا",
    flag: "🇸🇮",
    code: "SI",
    dialCode: "386",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "Solomon Islands",
    arabicName: "جزر سليمان",
    flag: "🇸🇧",
    code: "SB",
    dialCode: "677",
    minLength: 5,
    maxLength: 5,
  ),
  PhoneFieldCountryEntity(
    name: "Somalia",
    arabicName: "الصومال",
    flag: "🇸🇴",
    code: "SO",
    dialCode: "252",
    minLength: 8,
    maxLength: 8,
  ),
  PhoneFieldCountryEntity(
    name: "South Africa",
    arabicName: "جنوب أفريقيا",
    flag: "🇿🇦",
    code: "ZA",
    dialCode: "27",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "South Sudan",
    arabicName: "جنوب السودان",
    flag: "🇸🇸",
    code: "SS",
    dialCode: "211",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "South Georgia and the South Sandwich Islands",
    arabicName: "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
    flag: "🇬🇸",
    code: "GS",
    dialCode: "500",
    minLength: 15,
    maxLength: 15,
  ),
  PhoneFieldCountryEntity(
    name: "Spain",
    arabicName: "إسبانيا",
    flag: "🇪🇸",
    code: "ES",
    dialCode: "34",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Sri Lanka",
    arabicName: "سيريلانكا",
    flag: "🇱🇰",
    code: "LK",
    dialCode: "94",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Sudan",
    arabicName: "السودان",
    flag: "🇸🇩",
    code: "SD",
    dialCode: "249",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Suriname",
    arabicName: "سورينام",
    flag: "🇸🇷",
    code: "SR",
    dialCode: "597",
    minLength: 7,
    maxLength: 7,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Svalbard and Jan Mayen",
  //   flag: "🇸🇯",
  //   code: "SJ",
  //   dialCode: "47",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Eswatini",
  //   flag: "🇸🇿",
  //   code: "SZ",
  //   dialCode: "268",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  PhoneFieldCountryEntity(
    name: "Sweden",
    arabicName: "السويد",
    flag: "🇸🇪",
    code: "SE",
    dialCode: "46",
    minLength: 7,
    maxLength: 13,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Switzerland",
  //   flag: "🇨🇭",
  //   code: "CH",
  //   dialCode: "41",
  //   minLength: 12,
  //   maxLength: 12,
  // ),
  PhoneFieldCountryEntity(
    name: "Syrian Arab Republic",
    arabicName: "الجمهورية السورية",
    flag: "🇸🇾",
    code: "SY",
    dialCode: "963",
    minLength: 10,
    maxLength: 10,
  ),
  PhoneFieldCountryEntity(
    name: "Taiwan",
    arabicName: "تايوان",
    flag: "🇹🇼",
    code: "TW",
    dialCode: "886",
    minLength: 9,
    maxLength: 9,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Tajikistan",
  //   flag: "🇹🇯",
  //   code: "TJ",
  //   dialCode: "992",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Tanzania, United Republic of Tanzania",
  //   flag: "🇹🇿",
  //   code: "TZ",
  //   dialCode: "255",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Thailand",
  //   flag: "🇹🇭",
  //   code: "TH",
  //   dialCode: "66",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Timor-Leste",
  //   flag: "🇹🇱",
  //   code: "TL",
  //   dialCode: "670",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Togo",
  //   flag: "🇹🇬",
  //   code: "TG",
  //   dialCode: "228",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Tokelau",
  //   flag: "🇹🇰",
  //   code: "TK",
  //   dialCode: "690",
  //   minLength: 4,
  //   maxLength: 4,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Tonga",
  //   flag: "🇹🇴",
  //   code: "TO",
  //   dialCode: "676",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Trinidad and Tobago",
  //   flag: "🇹🇹",
  //   code: "TT",
  //   dialCode: "1868",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Turkmenistan",
  //   flag: "🇹🇲",
  //   code: "TM",
  //   dialCode: "993",
  //   minLength: 8,
  //   maxLength: 8,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Tuvalu",
  //   flag: "🇹🇻",
  //   code: "TV",
  //   dialCode: "688",
  //   minLength: 6,
  //   maxLength: 6,
  // ),
  PhoneFieldCountryEntity(
    name: "Uganda",
    arabicName: "اوغندا",
    flag: "🇺🇬",
    code: "UG",
    dialCode: "256",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Ukraine",
    arabicName: "اوكرانيا",
    flag: "🇺🇦",
    code: "UA",
    dialCode: "380",
    minLength: 9,
    maxLength: 9,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Uruguay",
  //   flag: "🇺🇾",
  //   code: "UY",
  //   dialCode: "598",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Uzbekistan",
  //   flag: "🇺🇿",
  //   code: "UZ",
  //   dialCode: "998",
  //   minLength: 9,
  //   maxLength: 9,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Vanuatu",
  //   flag: "🇻🇺",
  //   code: "VU",
  //   dialCode: "678",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Venezuela, Bolivarian Republic of Venezuela",
  //   flag: "🇻🇪",
  //   code: "VE",
  //   dialCode: "58",
  //   minLength: 10,
  //   maxLength: 10,
  // ),
  PhoneFieldCountryEntity(
    name: "Vietnam",
    arabicName: "فيتنام",
    flag: "🇻🇳",
    code: "VN",
    dialCode: "84",
    minLength: 11,
    maxLength: 11,
  ),
  // PhoneFieldCountryEntity(
  //   name: "Virgin Islands, British",
  //   flag: "🇻🇬",
  //   code: "VG",
  //   dialCode: "1284",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  // PhoneFieldCountryEntity(
  //   name: "Virgin Islands, U.S.",
  //   flag: "🇻🇮",
  //   code: "VI",
  //   dialCode: "1340",
  //   minLength: 7,
  //   maxLength: 7,
  // ),
  PhoneFieldCountryEntity(
    name: "Wallis and Futuna",
    arabicName: "واليس وفوتونا",
    flag: "🇼🇫",
    code: "WF",
    dialCode: "681",
    minLength: 6,
    maxLength: 6,
  ),
  PhoneFieldCountryEntity(
    name: "Zambia",
    arabicName: "زامبيا",
    flag: "🇿🇲",
    code: "ZM",
    dialCode: "260",
    minLength: 9,
    maxLength: 9,
  ),
  PhoneFieldCountryEntity(
    name: "Zimbabwe",
    arabicName: "زيمبابوي",
    flag: "🇿🇼",
    code: "ZW",
    dialCode: "263",
    minLength: 9,
    maxLength: 9,
  ),
];
// see: https://en.wikipedia.org/wiki/List_of_country_calling_codes
// for list of country/calling codes

class PhoneFieldCountryEntity extends Equatable {
  final String name;
  final String arabicName;
  final String flag;
  final String code;
  final String dialCode;
  final String regionCode;
  final int minLength;
  final int maxLength;
  final RegExp? numberRegexValidation;

  const PhoneFieldCountryEntity({
    required this.name,
    required this.flag,
    required this.arabicName,
    required this.code,
    required this.dialCode,
    required this.minLength,
    required this.maxLength,
    this.regionCode = "",
    this.numberRegexValidation,
  });

  String get fullCountryCode {
    return dialCode + regionCode;
  }

  String get displayCC {
    if (regionCode != "") {
      return "$dialCode $regionCode";
    }
    return dialCode;
  }

  @override
  List<Object?> get props => [
        name,
        arabicName,
        flag,
        code,
        dialCode,
        regionCode,
        minLength,
        maxLength,
        numberRegexValidation,
      ];
}
